"""
Text-to-speech helper for Cyclops Field Assistant.

The final system uses Android's native TextToSpeech engine on the headset.
This module prepares clean, structured TTS payloads from generated answer text.
It does not require a server-side speech synthesis model.
"""

from __future__ import annotations

import argparse
import json
import re
import time
from typing import Any, Dict, Optional


SUPPORTED_LANGUAGE_MAP = {
    "en": "en-US",
    "en-US": "en-US",
    "tr": "tr-TR",
    "tr-TR": "tr-TR",
    "de": "de-DE",
    "de-DE": "de-DE",
    "hu": "hu-HU",
    "hu-HU": "hu-HU",
    "sk": "sk-SK",
    "sk-SK": "sk-SK",
    "cs": "cs-CZ",
    "cs-CZ": "cs-CZ",
}


def normalize_language(language: Optional[str]) -> str:
    """
    Convert short language codes into Android-compatible locale codes.
    """
    if not language:
        return "en-US"

    return SUPPORTED_LANGUAGE_MAP.get(language, language)


def sanitize_tts_text(text: str) -> str:
    """
    Remove markdown/code formatting and collapse whitespace before TTS.
    """
    if text is None:
        return ""

    cleaned = str(text)

    # Remove fenced code blocks while keeping surrounding explanation clean.
    cleaned = re.sub(r"```.*?```", " ", cleaned, flags=re.DOTALL)

    # Convert markdown links [label](url) -> label.
    cleaned = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", cleaned)

    # Remove common markdown symbols.
    cleaned = cleaned.replace("**", "")
    cleaned = cleaned.replace("__", "")
    cleaned = cleaned.replace("`", "")

    # Remove bullet markers at line starts.
    cleaned = re.sub(r"^\s*[-*]\s+", "", cleaned, flags=re.MULTILINE)

    # Collapse whitespace.
    cleaned = re.sub(r"\s+", " ", cleaned).strip()

    return cleaned


def build_tts_payload(
    text: str,
    language: str = "en-US",
    utterance_id: Optional[str] = None,
    rate: float = 1.0,
    pitch: float = 1.0,
    interrupt: bool = True,
) -> Dict[str, Any]:
    """
    Build a structured payload that the Android app can speak with native TTS.

    Parameters
    ----------
    text:
        Answer text generated by the RAG module.
    language:
        Language or locale code, e.g. "en", "en-US", "tr", "de-DE".
    utterance_id:
        Optional unique id for tracking the spoken response.
    rate:
        Speech rate multiplier.
    pitch:
        Speech pitch multiplier.
    interrupt:
        If true, the client should stop any active speech before speaking this one.
    """
    clean_text = sanitize_tts_text(text)

    if not clean_text:
        raise ValueError("TTS text is empty after sanitization.")

    if utterance_id is None:
        utterance_id = f"tts_{int(time.time() * 1000)}"

    return {
        "type": "tts.speak",
        "utterance_id": utterance_id,
        "text": clean_text,
        "language": normalize_language(language),
        "rate": float(rate),
        "pitch": float(pitch),
        "interrupt": bool(interrupt),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a Cyclops TTS payload.")
    parser.add_argument("text", type=str, help="Text to speak.")
    parser.add_argument("--language", type=str, default="en-US", help="Language/locale code.")
    parser.add_argument("--rate", type=float, default=1.0, help="Speech rate.")
    parser.add_argument("--pitch", type=float, default=1.0, help="Speech pitch.")
    args = parser.parse_args()

    payload = build_tts_payload(
        text=args.text,
        language=args.language,
        rate=args.rate,
        pitch=args.pitch,
    )

    print(json.dumps(payload, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
